lolapp/urls.py
from django.urls import path
from .views import *


app_name= "lolapp"
urlpatterns = [

	#client side pages
	path('', HomeView.as_view(), name="home"),
	path('about-us/', AboutView.as_view(), name="about"),
	path('contact/', ContactView.as_view(), name="contact"),
	path('all-products/', AllProductsView.as_view(), name="allproducts"),
	path('product/<slug:slug>/', ProductDetailView.as_view(), name="productdetail"),

	path('add-to-cart-<int:pro_id>/', AddToCartView.as_view(), name="addtocart"),
	path('my-cart/', MyCartView.as_view(), name="mycart"),
	path('manage-cart/<int:cp_id>/', ManageCartView.as_view(), name="managecart"),
	path('empty-cart/', EmptyCartView.as_view(), name="emptycart"),

	path('checkout/', CheckoutView.as_view(), name="checkout"),
	path("khaltipay/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),

    path("esewapay/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),


	path('registration/',
		CustomerRegistrationView.as_view(), name="customerregistration"),

	path('logout/', CustomerLogoutView.as_view(), name="customerlogout"),
	path('login/', CustomerLoginView.as_view(), name="customerlogin"),

	path('profile/', CustomerProfileView.as_view(), name="customerprofile"),
	path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
		name="customerorderdetail"),
	path("search/", SearchView.as_view(), name="search"),

    path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
    path("password-reset/<email>/<token>/",
    	PasswordResetView.as_view(), name="passwordreset"),
    	
     path("review/<int:pro_id>/", ReviewView.as_view(), name='review'),
    # Admin Side pages

    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
    	name="adminorderdetail"),

    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("admin-order-<int:pk>-change/",
    	AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
    	name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(),
    	name="adminproductcreate"),



	] 

lolproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lolapp.urls')),


]


urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lolapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Khalti", "Khalti"),
    ("Esewa", "Esewa"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)


RATE_CHOICE=[
    ("1", "Very bad"),
    ("2", "poor"),
    ("3", "ok"),
    ("4","good"),
    ("5", "Excellent"),

]

class Review(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    product = models.ForeignKey(Product, models.CASCADE)
    comment = models.TextField(max_length=300)
    rate= models.IntegerField(default=0)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

templates/addtocart.html
{% extends 'base.html' %}

{% block title %} Add To Cart {% endblock %}

{% block content %}
<div class="container">
	<h3>Product added to cart successfully</h3>
</div>
{% endblock %}

templates/allproducts.html
{% extends 'base.html' %}


{% block title %} All Products{% endblock %}

{% block content %}
<div class="container">
		<p class="text-center"><b> <i>Here's your Local Items</p> <hr>
		{% for cat in allcategories %}
		<h3><b><i>{{cat.title}}</i></b></h3> <hr>   
		<div class="row mt-3"> 
			{% for p in cat.product_set.all %}
			<div class="col-md-3">
				<h3> <a href="{% url 'lolapp:productdetail' p.slug %}" title="">{{p.title}}</a></h3>  
				<img src="{{p.image.url}}" alt="" class="img-fluid" style="height:200px; object-fit: cover;">
				<p class="mt-3">Price:<strike>Rs. {{p.marked_price}}</strike> Rs.{{p.selling_price}}</p>
				<a href="{% url 'lolapp:addtocart' p.id %}" class="btn btn-info" title="">Add To Cart</a>
			</div>  
			{% endfor %}
		</div>
		{% endfor %}
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="{% url 'lolapp:home' %}">Lol-Sell</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'lolapp:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'lolapp:contact' %}">Contact</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Categories</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'lolapp:allproducts' %}">Livestokes</a>
                    <a class="dropdown-item" href="{% url 'lolapp:allproducts' %}">Local Products</a>
                    <a class="dropdown-item" href="{% url 'lolapp:allproducts' %}">Local Herbs</a>
                    <a class="dropdown-item" href="{% url 'lolapp:allproducts' %}">Local Mades</a>
                    <a class="dropdown-item" href="{% url 'lolapp:allproducts' %}">Local Fruits</a>

                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'lolapp:mycart' %}">Cart</a>
            </li>
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if request.user.customer %}
                <a class="dropdown-item" href="{% url 'lolapp:customerprofile' %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'lolapp:customerlogout' %}">Logout</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'lolapp:customerregistration' %}">Register</a>
                <a class="dropdown-item" href="{% url 'lolapp:customerlogin' %}">Login</a>
                {% endif %}
                </div>
            </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'lolapp:search' %}" method="GET">
            <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        </nav>
    <hr>

   
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>

templates/checkout.html
{% extends 'base.html' %}

{% block title %}Checkout {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Items in the cart</h3>
            <a href="{% url 'lolapp:mycart' %}">Cart Update</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-info">Create Order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block title %}Contact{% endblock%}
{% block content %}
<h4 class="text-center"> <b> <i>This is contact </i></b></h4>
<div class="container">
	<div class="contact-head">
		<div class="row">
			<div class="single-head">
				<div class="single-info">
					<i class="fa fa-phone"></i>
						<h4 class="title"> Call us Now:</h4>
						    <ul>
								<li>+977 9861980312</li>
								<li>+977 9848588734</li>
							</ul>
				</div>
				<div class="single-info">
					<i class="fa fa-envelope-open"></i>
					<h4 class="title">Email:</h4>
					
					<ul>
						<li><a href="">sachin10thapa@gmail.com</a></li>
						<li><a href="">support@yourwebsite.com</a></li>
					</ul>
				</div>
			
				<div class="single-info">
					<i class="fa fa-location-arrow"></i>
					<h4 class="title">Our Address:</h4>
						<ul>
							<li>balkumari-24, Lalitpur</li>
						</ul>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}

templates/customerprofile.html
{% extends 'base.html' %}

{% block title %}My Profile{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Detail Information</h3><hr>
            <p><span class="font-weight-bold">Name: </span> {{customer.full_name}}</p>
            <p><span class="font-weight-bold">Username: </span> {{customer.user.username}}</p>
            <p><span class="font-weight-bold">Email: </span> {{customer.user.email}}</p>
            <p><span class="font-weight-bold">Address: </span> {{customer.address}}</p>
            <p><span class="font-weight-bold">Joined on: </span> {{customer.joined_on}}</p>
        </div>
        <div class="col-md-8">
            <h3>Previous Orders</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID</th>
                        <th>Amount</th>
                        <th>Ordered on</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ord in orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'lolapp:customerorderdetail' ord.pk %}"> #ORDER_{{ord.id}}</a></td>
                        <td>{{ord.total}}</td>
                        <td>{{ord.created_at|timesince}} ago</td>
                        <td>{{ord.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/customerregistration.html
{% extends 'base.html'%}


{% block title %} Customer Registration {% endblock %}

{% block content %}
<style>
	.errorlist{
	color:red; }

</style>
	
</style>
<div class="container">
	<div class="row">
		<div class="col-md-6 mx-auto">
			<h3>Customer Registration Form</h3> <hr>
			<form action="" method="POST">
				{% csrf_token %}
				{{ form.as_p}}
				<button class="btn btn-info">Register As Customer</button>
			</form>	
			<h5>Already have account? <a href="{% url 'lolapp:customerlogin'%}">Login Here...!</a></h5>		
		</div>
		

	</div>
</div>
{% endblock %}

templates/esewapay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #myform{
            display: none;
        }
    </style>
</head>
<body>
    <h3 style="text-align: center;">You will be redirected to the esewa website..</h3>
    <form action="https://uat.esewa.com.np/epay/main" method="POST" id="myform">
        <input value="{{order.total}}" name="tAmt" type="hidden">
        <input value="{{order.total}}" name="amt" type="hidden">
        <input value="0" name="txAmt" type="hidden">
        <input value="0" name="psc" type="hidden">
        <input value="0" name="pdc" type="hidden">
        <input value="epay_payment" name="scd" type="hidden">
        <input value="order_{{order.id}}" name="pid" type="hidden">
        <input value="http://127.0.0.1:8000/esewa-verify/" type="hidden" name="su">
        <input value="{{request.build_absolute_uri}}" type="hidden" name="fu">
        <input value="Submit" type="submit">
    </form>

    <script>
        setTimeout(function(){
            document.getElementById("myform").submit()
        }, 500)
        
    </script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container">

    <h1 class="text-center"> <b> <i>Welcome to Lol-sell</i></b></h1>
    <hr>
    <div class="row mt-3">
        {% for p in product_list %}
        <div class="col-md-3 card">
            <div class="m-4">
                <h4><a href="{% url 'lolapp:productdetail' p.slug %}">{{p.title}}</a></h4>
                <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 200px; object-fit: contain;">
                <p class="mt-3">Price: <strike>Rs. {{p.marked_price}}</strike> Rs. {{p.selling_price}}</p>
                <a href="{% url 'lolapp:addtocart' p.id %}" class="btn btn-primary">Add To Cart</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <nav aria-label="...">
        <ul class="pagination">
            {% if product_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ product_list.previous_page_number }}">Previous</a>
              </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            {% endif %}

            {% for i in product_list.paginator.page_range %}
            {% if i == product_list.number %}
            <li class="page-item active"><a class="page-link">{{i}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}

            {% if product_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ product_list.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
            {% endif %}
        </ul>
      </nav>

</div>
{% endblock %}

templates/khaltipay.html
<html>
<head>
    <script src="https://unpkg.com/khalti-checkout-web@latest/dist/khalti-checkout.iffe.js"></script>
</head>
<body>
    <h3>Your order amount is Rs. {{order.total}}</h3>
    
    <button id="payment-button">Pay with Khalti</button>
    <a href="/">Go to Home page</a>

    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>
        var config = {
            // replace the publicKey with yours
            "publicKey": "test_public_key_dc74e0fd57cb46cd93832aee0a390234",
            "productIdentity": "order_{{order.id}}",
            "productName": "order_{{order.id}}",
            "productUrl": "http://localhost:8000",
            "paymentPreference": [
                "MOBILE_BANKING",
                "KHALTI",
                "EBANKING",
                "CONNECT_IPS",
                "SCT",
                ],
            "eventHandler": {
                onSuccess (payload) {
                    // hit merchant api for initiating verfication
                    axios.get("/khalti-verify/", {
                        params: {
                            "token": payload.token,
                            "amount": payload.amount,
                            "order_id": "{{order.id}}"
                        }
                    }).then(function(resp){
                        if (resp.data.success == true){
                            alert("Thanks. Payment Completed Successfully")
                            location.href = "/"
                        }else{
                            alert("Sorry. Error occurred")
                            location.href = "{{request.build_absolute_uri}}"
                        }
                    })
                },
                onError (error) {
                    console.log(error);
                },
                onClose () {
                    console.log('widget is closing');
                }
            }
        };

        var checkout = new KhaltiCheckout(config);
        var btn = document.getElementById("payment-button");
        btn.onclick = function () {
            // minimum transaction amount must be 10, i.e 1000 in paisa.
            checkout.show({amount: {{order.total}}*100});
        }
    </script>
    <!-- Paste this code anywhere in you body tag -->
</body>
</html>

templates/mycart.html
{% extends 'base.html' %}


{% block title %} My Cart {% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-8">
			<h3>Things in My Cart</h3>
			<table class="table">
				<thead>
					<tr>
						<th>S.N</th>
						<th>Product</th>
						<th>Rate</th>
						<th>Quantity</th>
						<th>Subtotal</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					{% for cp in cart.cartproduct_set.all %}
					<tr>
						<td>{{forloop.counter}}</td>
						<td>{{cp.product.title}}</td>
						<td>{{cp.rate}}</td>
						<td>{{cp.quantity}}</td>
						<td>{{cp.subtotal}}</td>
						<td>
							<a href="{% url 'lolapp:managecart' cp.id %}?action=inc"class="btn btn-primary">+</a>
							<a href="{% url 'lolapp:managecart' cp.id %}?action=dec"class="btn btn-warning">-</a>
							<a href="{% url 'lolapp:managecart' cp.id %}?action=rmv"class="btn btn-danger">X</a>
						</td>
					</tr>
					{% endfor %}
					<tr>
						<th colspan="4">Total</th>
						<th>{{cart.total}}</th>
						{% if cart.cartproduct_set.all %}
						<th><a href="{% url 'lolapp:emptycart' %}"> Empty Cart</a></th>
						{% endif %}
					</tr>
					{% if cart.cartproduct_set.all %}
					<tr> 
						<th><a class="btn btn-info" href="{% url 'lolapp:checkout' %}">Checkout</a></th>
					</tr>
					{% endif %}
				</tbody>
			</table>
			 
		</div>
		
	</div>
	
</div>

{% endblock %}

templates/productdetail.html
{% extends 'base.html' %}

{% block title %}{{product.title}}{% endblock %}

{% block content %}
<div class="container">
    <h3>Product: {{product.title}}</h3><hr>
    <div class="row">
        <div class="col-md-4"> 
            <img src="{{product.image.url}}" alt="" class="img-fluid">
            <div class="row">
                {% for pi in product.productimage_set.all %}
                <div class="col-md-4 p-3">
                    <a href="{{pi.image.url}}" target="_blank">
                        <img src="{{pi.image.url}}" class="img-fluid" style="height: 100px; object-fit: contain;" alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8">
            <h4>{{product.title}} (Viewed  {{product.view_count}}  times)</h4>
            <h5>Category: {{product.category}}</h5>
            <h5>Price: <strike>Rs. {{product.marked_price}}</strike> Rs. {{product.selling_price}}</h5>
            <a href="{% url 'lolapp:addtocart' product.id %}" class="btn btn-info">Add To Cart</a>
            <hr>
            <p class="text-info">Warranty: {{product.warranty}}</p>
            <p class="text-info">Return Policy:{{product.return_policy}}</p>
            <hr>
            <p>{{product.description}}</p>
        </div>
    </div>

</div>
{% endblock %}

templates/rating.html
{% extends 'base.html' %}

{% block content %}
{% comment %} 
        <div class = 'container' style =" margin:100px;">
        <div class = "row">
            <div class = 'col-md-6'>
                <h3> </h3>
               
                 <table class='table'> 
                          <thead>
                              <tr>
                              
                                <th>Image</th>
                                <th>Product</th>
                                <th>Price</th>       
                              </tr>
                          </thead>
                          <tbody>
                            
                              <tr>
                                <td><img src="{{products.image.url}} " style= " height:60px;width:60px;" ></td>
                                <td>{{products.title}}</td>
                                <td>{{products.price}}</td> 
                               </tr> 
                              
                    </tbody>
                </table>
                
        </div>   {% endcomment %}



        <div class = 'container' style="margin:80px">
                
                <h4>{{products.title}}:</h4>   
                  <div class ="container">
                        <div class="row " >
                            <div class='col-md-4'>
                            <div class='m-2'>
                                <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                                    <img
                                        src="{{products.image.url}} " class="img-fluid" style=" height:200px; object-fit:cover;"
                                      
                                    >
                                    <a href="#!">
                                    <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                    </a>
                                  </div>
                                    <div class="card-body">
                                      <h5 class="card-title">{{product.title}}</h5>
                                      <p class="card-text">
                                       {{products.description}}
                                      </p>
                                <hr/>
                                      <h5 style='display: inline-block;'> 
                                      Rs.{{products.price|floatformat:2}}</h5>
                                    </div>
                                  </div>
                          
                                </div>

                                 <div class="col-md-6" >
                <h3> Your Reviews please</h3>
                <form action="" method='POST'>
                    {% csrf_token %}
                    {{form.as_p}}
                <button class ='btn btn-primary'>Submit </button>
            </form>
        </div>
                            
 

            
           
    </div>  
 </div>
   
{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block title %}Search {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for <span class="text-info">"{{request.GET.keyword}}"</span></h3>
            <hr>
            {% for result in results %}
            <div class="row">
                <div class="col-md-3">
                    <img src="{{result.image.url}}" class="img-fluid" alt="">
                </div>
                <div class="col-md-9">
                    <h4><a href="{% url 'lolapp:productdetail' result.slug %}">{{result.title}}</a></h4>
                    <p>{{result.description|truncatewords:50}}</p>
                    <p>Return Policy: {{result.return_policy}}</p>
                    <a href="{% url 'lolapp:addtocart' result.id %}" class="btn btn-primary">Add To Cart</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}